"""
database.py - SQLite database setup and ORM models
"""
from datetime import datetime, timezone
from sqlalchemy import (
    create_engine, Column, Integer, String, Float,
    DateTime, Text, Boolean, Index,
)
from sqlalchemy.orm import declarative_base, sessionmaker, Session
from backend.config import DATABASE_URL

# ── Engine & Session ──────────────────────────────────────────────────────────
engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False},  # SQLite-specific
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def _utcnow():
    return datetime.now(timezone.utc)


# ── Models ────────────────────────────────────────────────────────────────────

class LogEntry(Base):
    """Normalized log entry parsed from raw log files."""
    __tablename__ = "log_entries"

    id         = Column(Integer, primary_key=True, index=True)
    timestamp  = Column(DateTime, nullable=False, index=True)
    source_ip  = Column(String(45), nullable=False, index=True)   # IPv6-safe
    action     = Column(String(16))   # GET, POST, FAILED_LOGIN, etc.
    path       = Column(Text)
    status     = Column(Integer)
    bytes_sent = Column(Integer, default=0)
    log_type   = Column(String(16))   # apache | ssh | syslog
    raw        = Column(Text)
    country    = Column(String(64))
    city       = Column(String(64))
    created_at = Column(DateTime, default=_utcnow)

    __table_args__ = (
        Index("ix_log_ip_time", "source_ip", "timestamp"),
    )


class Alert(Base):
    """Security alert generated by rule or ML engine."""
    __tablename__ = "alerts"

    id          = Column(Integer, primary_key=True, index=True)
    timestamp   = Column(DateTime, nullable=False, default=_utcnow, index=True)
    source_ip   = Column(String(45), nullable=False, index=True)
    alert_type  = Column(String(64), nullable=False)   # BRUTE_FORCE, DDOS, …
    description = Column(Text)
    severity    = Column(String(8))    # LOW | MEDIUM | HIGH
    risk_score  = Column(Float, default=0.0)
    engine      = Column(String(8))    # RULE | ML
    resolved    = Column(Boolean, default=False)
    country     = Column(String(64))
    created_at  = Column(DateTime, default=_utcnow)

    __table_args__ = (
        Index("ix_alert_ip_type", "source_ip", "alert_type"),
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def get_db() -> Session:
    """FastAPI dependency: yields a DB session and closes it afterwards."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db() -> None:
    """Create all tables (idempotent)."""
    Base.metadata.create_all(bind=engine)
